In [ ]:
import pandas as pd

In [ ]:
dados = pd.read_csv('https://raw.githubusercontent.com/dadosgovbr/catalogos-dados-brasil/refs/heads/master/dados/catalogos.csv')

In [ ]:
dados

,Título,URL,Município,UF,Esfera,Poder,Solução
0,Alagoas em dados e informações,http://dados.al.gov.br/,NaN,AL,Estadual,Executivo,CKAN
1,Fortaleza Dados Abertos,http://dados.fortaleza.ce.gov.br/,Fortaleza,CE,Municipal,Executivo,CKAN
2,Dados abertos – TCM-CE,http://api.tcm.ce.gov.br/,NaN,CE,Estadual,Legislativo,Interna
3,Dados abertos Distrito Federal,http://dados.df.gov.br/,NaN,DF,Estadual,Executivo,CKAN
4,Dados abertos – Governo do ES,https://transparencia.es.gov.br/DadosAbertos/B...,NaN,ES,Estadual,Executivo,Interna
5,Dados abertos – Goiás Transparente,http://www.transparencia.go.gov.br/portaldatra...,NaN,GO,Estadual,Executivo,Interna
6,Dados abertos – Assembleia de Minas,http://dadosabertos.almg.gov.br/ws/ajuda/sobre,NaN,MG,Estadual,Legislativo,Interna
7,Dados abertos – Estado de MG,http://www.dados.mg.gov.br,NaN,MG,Estadual,Executivo,CKAN
8,Dados abertos do SAGRES – TCE/PB,http://portal.tce.pb.gov.br/dados-abertos-do-s...,NaN,PB,Estadual,Legislativo,Interna
9,Dados abertos – Governo de Pernambuco,http://www.dadosabertos.pe.gov.br/,NaN,PE,Estadual,Executivo,Interna
10,Dados Recife,http://dados.recife.pe.gov.br,Recife,PE,Municipal,Executivo,CKAN
11,Dados Abertos Curitiba,http://www.curitiba.pr.gov.br/dadosabertos/,Curitiba,PR,Municipal,Executivo,Interna
12,data.rio,http://data.rio/,Rio de Janeiro,RJ,Municipal,Executivo,CKAN
13,Dados Geográficos Abertos da Cidade do Rio de ...,http://portalgeo.pcrj.opendata.arcgis.com/,Rio de Janeiro,RJ,Municipal,Executivo,ArcGIS
14,Dados RS,http://dados.rs.gov.br/,NaN,RS,Estadual,Executivo,CKAN
15,Dados Abertos SC,https://dados.sc.gov.br/,Santa Catarina,SC,Estadual,Executivo,CKAN
16,Dados Abertos POA,https://dados.portoalegre.rs.gov.br/,Porto Alegre,RS,Municipal,Executivo,CKAN
17,Governo Aberto SP,http://www.governoaberto.sp.gov.br/,NaN,SP,Estadual,Executivo,CKAN
18,Programa de Dados Abertos do Parlamento,http://www.camara.sp.gov.br/transparencia/dado...,São Paulo,SP,Municipal,Legislativo,Interna
19,Dados Abertos Legislativos – Senado Federal,http://dadosabertos.senado.gov.br/,NaN,NaN,Federal,Legislativo,Interna
20,Dados abertos da Câmara dos Deputados,https://dadosabertos.camara.leg.br/,NaN,NaN,Federal,Legislativo,Interna
21,Dados Abertos TCE-RS,http://dados.tce.rs.gov.br/,NaN,RS,Estadual,Legislativo,CKAN
22,Dados Abertos MPRS,http://dados.mprs.mp.br/,NaN,RS,Estadual,NaN,Interna
23,Portal da Transparência Municipal,http://transparencia.tce.sp.gov.br/,NaN,SP,Municipal,Legislativo,Interna
24,Portal dos Dados Abertos TCE/RN,http://apidadosabertos.tce.rn.gov.br/,NaN,RN,Estadual,Legislativo,Interna
25,Portal de Dados Abertos da Cidade de São Paulo,http://dados.prefeitura.sp.gov.br/,São Paulo,SP,Municipal,Executivo,CKAN
26,Câmara de Itabira – Dados Abertos,http://www.itabira.cam.mg.gov.br/dados-abertos,Itabira,MG,Municipal,Legislativo,Interna
27,Portal dos Dados Abertos da Alesp – al.sp.gov.br,https://www.al.sp.gov.br/dados-abertos/,NaN,SP,Estadual,Legislativo,Interna
28,Transparência Anápois – Dados Abertos,http://www.transparencia.anapolis.go.gov.br:80...,Anápolis,GO,Municipal,Executivo,Interna
29,Download de Bases – TRANSPARÊNCIA,http://www.transparencia.mt.gov.br/downloads-d...,NaN,MT,Estadual,Executivo,Interna
30,Dados PB,http://dados.pb.gov.br,NaN,PB,Estadual,Executivo,Interna
31,Portal da Transparência – Dados Abertos,http://transparencia.campinas.sp.gov.br/,Campinas,SP,Municipal,Executivo,Interna
32,Dados Abertos – TCEMG,https://dadosabertos.tce.mg.gov.br/,NaN,MG,Estadual,Legislativo,Interna
33,Dados Abertos – Cerará Transparente,https://cearatransparente.ce.gov.br/portal-da-...,NaN,CE,Estadual,Executivo,Interna
34,Portal da Transparência e Mobilidade Urbana de...,http://dados.natal.br/,Natal,RN,Municipal,Executivo,CKAN
35,Dados Abertos – Portal da Transparência de Per...,http://web.transparencia.pe.gov.br/dados-abertos/,NaN,PE,Estadual,Executivo,CKAN
36,Dados Abertos – Tribunal de Contas do Estado d...,https://www.tce.pe.gov.br/internet/index.php/d...,NaN,PE,Estadual,Legislativo,Interna
37,Portal de Dados Abertos – Prefeitura de Belo H...,https://dados.pbh.gov.br/,Belo Horizonte,MG,Municipal,Executivo,CKAN
38,Portal de Dados Abertos da Câmara Legislativa ...,http://dadosabertos.cl.df.gov.br/,NaN,DF,Estadual,Legislativo,Interna

In [ ]:
dados['UF']

0      AL
1      CE
2      CE
3      DF
4      ES
5      GO
6      MG
7      MG
8      PB
9      PE
10     PE
11     PR
12     RJ
13     RJ
14     RS
15     SC
16     RS
17     SP
18     SP
19    NaN
20    NaN
21     RS
22     RS
23     SP
24     RN
25     SP
26     MG
27     SP
28     GO
29     MT
30     PB
31     SP
32     MG
33     CE
34     RN
35     PE
36     PE
37     MG
38     DF
Name: UF, dtype: object

In [ ]:
dados.head()

,Título,URL,Município,UF,Esfera,Poder,Solução
0,Alagoas em dados e informações,http://dados.al.gov.br/,NaN,AL,Estadual,Executivo,CKAN
1,Fortaleza Dados Abertos,http://dados.fortaleza.ce.gov.br/,Fortaleza,CE,Municipal,Executivo,CKAN
2,Dados abertos – TCM-CE,http://api.tcm.ce.gov.br/,NaN,CE,Estadual,Legislativo,Interna
3,Dados abertos Distrito Federal,http://dados.df.gov.br/,NaN,DF,Estadual,Executivo,CKAN
4,Dados abertos – Governo do ES,https://transparencia.es.gov.br/DadosAbertos/B...,NaN,ES,Estadual,Executivo,Interna

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Título     39 non-null     object
 1   URL        39 non-null     object
 2   Município  14 non-null     object
 3   UF         37 non-null     object
 4   Esfera     39 non-null     object
 5   Poder      38 non-null     object
 6   Solução    39 non-null     object
dtypes: object(7)
memory usage: 2.3+ KB

In [ ]:
dados.describe()

,Título,URL,Município,UF,Esfera,Poder,Solução
count,39,39,14,37,39,38,39
unique,39,39,12,15,3,2,3
top,Alagoas em dados e informações,http://dados.al.gov.br/,Rio de Janeiro,SP,Estadual,Executivo,Interna
freq,1,1,2,6,23,24,23